In [24]:
import sqlite3
import pandas as pd
import os


# CSV

csv_path = "recursos_humanos.csv"

df = pd.read_csv(csv_path)

df.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low

In [26]:
# Base de datos RH.db

db_path = "RH.db"

conn = sqlite3.connect(db_path)


# CSV a la tabla "Detalle"

df.to_sql("Detalle", conn, if_exists="replace", index=False)

14999

In [30]:
# Se despliegan las columnas sales, salary y satisfaction en orden descendente de acuerdo al campo “satisfaction_level"

consulta1 = """
SELECT sales, salary, satisfaction_level
FROM Detalle
ORDER BY satisfaction_level DESC;
"""

q1 = pd.read_sql_query(consulta1, conn)
q1

           sales  salary  satisfaction_level
0      technical     low                1.00
1      technical     low                1.00
2        support     low                1.00
3          sales     low                1.00
4      technical     low                1.00
...          ...     ...                 ...
14994  technical     low                0.09
14995    support     low                0.09
14996      sales     low                0.09
14997  technical  medium                0.09
14998    support     low                0.09

[14999 rows x 3 columns]

In [16]:
# Promedio obtenido de la última evaluación para cada departamento

consulta2 = """
SELECT sales, AVG(last_evaluation) AS promedio_ultima_evaluacion
FROM Detalle
GROUP BY sales;
"""

q2 = pd.read_sql_query(consulta2, conn)
q2

         sales  promedio_ultima_evaluacion
0           IT                    0.716830
1        RandD                    0.712122
2   accounting                    0.717718
3           hr                    0.708850
4   management                    0.724000
5    marketing                    0.715886
6  product_mng                    0.714756
7        sales                    0.709717
8      support                    0.723109
9    technical                    0.721099

In [32]:
# Departamentos para los cuales el promedio de accidentes de trabajo sea mayor a 0.15

consulta3 = """
SELECT sales, AVG(Work_accident) AS promedio_accidentes
FROM Detalle
GROUP BY sales
HAVING AVG(Work_accident) > 0.15
"""
pd.read_sql(consulta3, conn)

        sales  promedio_accidentes
0       RandD             0.170267
1  management             0.163492
2   marketing             0.160839
3     support             0.154778

In [34]:
# ¿Cómo cambiaría su consulta si lo que quisiera mostrar es aquellos departamentos donde el número de accidentes sea mayor que 200?

# Se cambiaría el AVG, por el SUM